### ISSUE TITLE
No error message when adding a word entry with invalid url

### ISSUE THREAD

**Issue by lmuehlboeck** [TGM-HIT/sew9-2425-worttrainer-leanderlist#1]
When I click on "Add Entry" and enter an invalid url in the second dialog, there is no error message although the word entry is not added to the Worttrainer. This is not a very good UX!

**Comment by leanderlist** [comment]
Thank you for the report! I will look into it, and try to resolve this issue as soon as possible.

**Comment by leanderlist** [comment]
Thank you for your report! I will look into it and try to resolve this issue as soon as possible.

**Comment by leanderlist** [comment]
test #1fc093613c5e99dc7f09fb37020dfcaead8eaf72

**Comment by leanderlist** [comment]
test 24efa5b4d8903fbe035a268f82151cf44dd3a535

**Comment by leanderlist** [comment]
This Issue got resolved with 24efa5b4d8903fbe035a268f82151cf44dd3a535
